### ISSUE TITLE
PathLSTM giving package cast error

### ISSUE THREAD

**Issue by Vyso** [Vyso/TheCleverbot#1]
Hey, @microth
I'm trying to use the PathLSTM model, but I'm still getting this issue : https://github.com/microth/PathLSTM/issues/13

Then I tried copying the 'features' subfolder from uk.ac.ed.inf.srl to se.ith.cs.srl, but I get the following error.

**************************************************************************************************************
Loading pipeline from C:\Users\Vyso\Downloads\NLP\SRL\SEMAFOR\absSemafor\LTH\wttv\PathLSTM-pre-illinois-built\CoNLL2009-ST-English-ALL.anna-3.3.srl-4.1.srl.model
Exception in thread "main" java.lang.ClassCastException: se.lth.cs.srl.features.FeatureGenerator cannot be cast to uk.ac.ed.inf.srl.features.FeatureGenerator
	at se.lth.cs.srl.pipeline.Pipeline.fromZipFile(Pipeline.java:192)
	at se.lth.cs.srl.pipeline.Reranker.<init>(Reranker.java:61)
	at se.lth.cs.srl.Parse.main(Parse.java:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)

Process finished with exit code 1
***********************************************************************************************************
Is this problem resolvable by me, or are the classes missing? Could you instruct me on how I could get out of this?

Thank You.
Best Regards.
Vishnu

**Comment by microth** [comment]
Hi Vishnu,

It looks like you are trying to use a SRL model from mate-tools, rather than the PathLSTM model that I developed. Please use the SRL model file that can be downloaded here (cf. README):

  https://drive.google.com/uc?id=0B5aLxfs6OvZBYUk2b0hLZjNqY3c&export=download

There is no need to copy class files. They are part of the right package.

Cheers,
Michael
